#!/usr/bin/env python3
"""Convert palettes.json to source/PalettesGenerated.mc.

Run before monkeyc to keep the watch-side palette list in sync with the
JSON edited by the web tool. Skips regeneration if the .mc is newer than
the JSON so it's cheap to chain into every build.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(ROOT, "palettes.json")
OUT_PATH = os.path.join(ROOT, "source", "PalettesGenerated.mc")


def needs_regen() -> bool:
    if not os.path.exists(OUT_PATH):
        return True
    return os.path.getmtime(JSON_PATH) > os.path.getmtime(OUT_PATH)


def main() -> int:
    if not os.path.exists(JSON_PATH):
        sys.stderr.write(f"missing {JSON_PATH}\n")
        return 1
    if not needs_regen():
        return 0
    with open(JSON_PATH) as f:
        palettes = json.load(f)

    if not palettes:
        sys.stderr.write("palettes.json must contain at least one palette\n")
        return 1

    lines = [
        "// GENERATED by gen-palettes.py — do not edit by hand.",
        "// Source of truth: palettes.json (edit via palette-editor.html).",
        "import Toybox.Lang;",
        "",
        "function getPalettes() as Array {",
        "  return [",
    ]
    for i, p in enumerate(palettes):
        name = p["name"].replace('"', '\\"')
        colors = ", ".join(p["colors"])
        comma = "," if i < len(palettes) - 1 else ""
        lines.append(f"    {{ :name => \"{name}\", :colors => [{colors}] }}{comma}")
    lines += [
        "  ];",
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH} ({len(palettes)} palettes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
