#!/usr/bin/env python3
"""Convert presets/shipped.json to source/ShippedPresetsGenerated.mc.

Run before monkeyc. Skips regeneration if the .mc is newer than the
JSON so it's cheap to chain into every build.
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
JSON_PATH = os.path.join(SCRIPT_DIR, "shipped.json")
OUT_PATH = os.path.join(PROJECT_ROOT, "source", "ShippedPresetsGenerated.mc")

KEYS = [
    "BackgroundColor",
    "TimeColor",
    "GraphNumberColor",
    "HRMin",
    "HRMax",
    "HRStep",
    "PaletteIndex",
    "GraphBandPixels",
    "ShowGraphAxis",
    "HeartGraphMinutes",
    "MinimalMode",
]


def needs_regen() -> bool:
    if not os.path.exists(OUT_PATH):
        return True
    return os.path.getmtime(JSON_PATH) > os.path.getmtime(OUT_PATH)


def fmt_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    return str(v)


def main() -> int:
    if not os.path.exists(JSON_PATH):
        sys.stderr.write(f"missing {JSON_PATH}\n")
        return 1
    if not needs_regen():
        return 0
    with open(JSON_PATH) as f:
        presets = json.load(f)

    lines = [
        "// GENERATED by presets/gen-shipped.py — do not edit by hand.",
        "// Source of truth: presets/shipped.json.",
        "import Toybox.Lang;",
        "",
        "function getShippedPresets() as Array {",
        "  return [",
    ]
    for i, p in enumerate(presets):
        name = p["name"].replace('"', '\\"')
        v = p["values"]
        # Verify all expected keys are present (fail fast on bad JSON).
        missing = [k for k in KEYS if k not in v]
        if missing:
            sys.stderr.write(f"preset {name!r} missing keys: {missing}\n")
            return 1
        pairs = ", ".join(f"\"{k}\" => {fmt_value(v[k])}" for k in KEYS)
        comma = "," if i < len(presets) - 1 else ""
        lines.append(f"    {{ \"name\" => \"{name}\", \"values\" => {{ {pairs} }} }}{comma}")
    lines += [
        "  ];",
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH} ({len(presets)} presets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
